import type {
  Property,
  Tenant,
  Reservation,
  Invoice,
  DashboardMetrics,
  MonthlyRevenue,
  MaintenanceAlert,
  CheckInOut,
  PropertyPerformance,
  MaintenanceRecord,
  PropertyDocument,
  CommunicationLog,
  GuestProfile,
  PaymentRecord,
  ReservationDocument,
  ReservationDetail,
  BlockedDate,
  Expense,
  FinancialOverview,
  ProfitLossData,
  OccupancyRateData,
  Transaction,
  RevenueTimelineData,
  ADRData,
  PropertyPerformanceMetrics,
  Budget,
  RecurringExpense,
  ExpenseTrendData,
  PropertyExpenseComparison,
} from "./types"

export const mockProperties: Property[] = [
  {
    id: "1",
    name: "Sunset Villa",
    address: "Kololi, Serrekunda",
    status: "occupied",
    standardRate: 15000,
    imageUrl: "/modern-luxury-villa-sunset.jpg",
  },
  {
    id: "2",
    name: "Ocean View Apartment",
    address: "Cape Point, Bakau",
    status: "vacant",
    standardRate: 12000,
    imageUrl: "/ocean-view-apartment.jpg",
  },
  {
    id: "3",
    name: "Garden House",
    address: "Fajara, Kanifing",
    status: "occupied",
    standardRate: 18000,
    imageUrl: "/tropical-garden-house.jpg",
  },
  {
    id: "4",
    name: "City Center Studio",
    address: "Westfield, Serrekunda",
    status: "maintenance",
    standardRate: 8000,
    imageUrl: "/modern-studio-apartment.png",
    maintenanceEndDate: "2025-03-15",
  },
  {
    id: "5",
    name: "Beachfront Bungalow",
    address: "Kotu, Serrekunda",
    status: "vacant",
    standardRate: 20000,
    imageUrl: "/beachfront-bungalow.png",
  },
  {
    id: "6",
    name: "Palm Residence",
    address: "Bijilo, Kanifing",
    status: "occupied",
    standardRate: 16000,
    imageUrl: "/palm-tree-residence.jpg",
  },
]

export const mockTenants: Tenant[] = [
  {
    id: "1",
    name: "Fatou Jallow",
    email: "fatou.jallow@email.com",
    phone: "+220 123 4567",
    whatsapp: "+220 123 4567",
  },
  {
    id: "2",
    name: "Lamin Ceesay",
    email: "lamin.ceesay@email.com",
    phone: "+220 234 5678",
    whatsapp: "+220 234 5678",
  },
  {
    id: "3",
    name: "Mariama Sanneh",
    email: "mariama.sanneh@email.com",
    phone: "+220 345 6789",
    whatsapp: "+220 345 6789",
  },
]

export const mockReservations: Reservation[] = [
  {
    id: "1",
    propertyId: "1",
    tenantId: "1",
    checkIn: "2025-02-01",
    checkOut: "2025-02-28",
    negotiatedRate: 14000,
    paymentStatus: "paid",
    createdAt: "2025-01-15",
  },
  {
    id: "2",
    propertyId: "3",
    tenantId: "2",
    checkIn: "2025-02-10",
    checkOut: "2025-03-10",
    negotiatedRate: 17000,
    paymentStatus: "pending",
    createdAt: "2025-01-20",
  },
  {
    id: "3",
    propertyId: "6",
    tenantId: "3",
    checkIn: "2025-02-15",
    checkOut: "2025-03-15",
    negotiatedRate: 15500,
    paymentStatus: "paid",
    createdAt: "2025-01-25",
  },
  {
    id: "4",
    propertyId: "2",
    tenantId: "1",
    checkIn: "2025-02-05",
    checkOut: "2025-02-20",
    negotiatedRate: 12000,
    paymentStatus: "paid",
    createdAt: "2025-01-18",
  },
  {
    id: "5",
    propertyId: "5",
    tenantId: "2",
    checkIn: "2025-02-12",
    checkOut: "2025-02-26",
    negotiatedRate: 20000,
    paymentStatus: "pending",
    createdAt: "2025-01-22",
  },
  {
    id: "6",
    propertyId: "1",
    tenantId: "3",
    checkIn: "2025-03-01",
    checkOut: "2025-03-31",
    negotiatedRate: 15000,
    paymentStatus: "pending",
    createdAt: "2025-02-01",
  },
  {
    id: "7",
    propertyId: "3",
    tenantId: "1",
    checkIn: "2025-03-15",
    checkOut: "2025-04-15",
    negotiatedRate: 18000,
    paymentStatus: "pending",
    createdAt: "2025-02-05",
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: "1",
    reservationId: "1",
    amount: 14000,
    issueDate: "2025-02-01",
    dueDate: "2025-02-05",
    status: "paid",
  },
  {
    id: "2",
    reservationId: "2",
    amount: 17000,
    issueDate: "2025-02-10",
    dueDate: "2025-02-15",
    status: "pending",
  },
]

export const mockDashboardMetrics: DashboardMetrics = {
  totalProperties: 6,
  occupied: 3,
  vacant: 2,
  upcomingRevenue: 46500,
  ytdRealizedRevenue: 125000,
  occupancyRate: 60,
  currentMonthRevenue: 46500,
  lastMonthRevenue: 42000,
}

export const mockMonthlyRevenue: MonthlyRevenue[] = [
  {
    month: "JAN",
    realized: 42000,
    future: 0,
    byProperty: {
      "1": { realized: 14000, future: 0 },
      "2": { realized: 8000, future: 0 },
      "3": { realized: 12000, future: 0 },
      "4": { realized: 3500, future: 0 },
      "5": { realized: 2500, future: 0 },
      "6": { realized: 8000, future: 0 },
    },
  },
  {
    month: "FEB",
    realized: 46500,
    future: 0,
    byProperty: {
      "1": { realized: 15000, future: 0 },
      "2": { realized: 9500, future: 0 },
      "3": { realized: 13000, future: 0 },
      "4": { realized: 4000, future: 0 },
      "5": { realized: 3000, future: 0 },
      "6": { realized: 9000, future: 0 },
    },
  },
  {
    month: "MAR",
    realized: 0,
    future: 48000,
    byProperty: {
      "1": { realized: 0, future: 15000 },
      "2": { realized: 0, future: 10000 },
      "3": { realized: 0, future: 14000 },
      "4": { realized: 0, future: 4200 },
      "5": { realized: 0, future: 3500 },
      "6": { realized: 0, future: 9000 },
    },
  },
  {
    month: "APR",
    realized: 0,
    future: 52000,
    byProperty: {
      "1": { realized: 0, future: 16000 },
      "2": { realized: 0, future: 11000 },
      "3": { realized: 0, future: 15000 },
      "4": { realized: 0, future: 4500 },
      "5": { realized: 0, future: 4000 },
      "6": { realized: 0, future: 10000 },
    },
  },
  {
    month: "MAY",
    realized: 0,
    future: 45000,
    byProperty: {
      "1": { realized: 0, future: 14000 },
      "2": { realized: 0, future: 9000 },
      "3": { realized: 0, future: 13000 },
      "4": { realized: 0, future: 3800 },
      "5": { realized: 0, future: 3200 },
      "6": { realized: 0, future: 9000 },
    },
  },
  {
    month: "JUN",
    realized: 0,
    future: 50000,
    byProperty: {
      "1": { realized: 0, future: 15500 },
      "2": { realized: 0, future: 10500 },
      "3": { realized: 0, future: 14000 },
      "4": { realized: 0, future: 4300 },
      "5": { realized: 0, future: 3700 },
      "6": { realized: 0, future: 10000 },
    },
  },
  {
    month: "JUL",
    realized: 0,
    future: 47000,
    byProperty: {
      "1": { realized: 0, future: 14500 },
      "2": { realized: 0, future: 9500 },
      "3": { realized: 0, future: 13500 },
      "4": { realized: 0, future: 4100 },
      "5": { realized: 0, future: 3400 },
      "6": { realized: 0, future: 9500 },
    },
  },
  {
    month: "AUG",
    realized: 0,
    future: 51000,
    byProperty: {
      "1": { realized: 0, future: 15800 },
      "2": { realized: 0, future: 10700 },
      "3": { realized: 0, future: 14500 },
      "4": { realized: 0, future: 4600 },
      "5": { realized: 0, future: 3900 },
      "6": { realized: 0, future: 10000 },
    },
  },
  {
    month: "SEP",
    realized: 0,
    future: 49000,
    byProperty: {
      "1": { realized: 0, future: 15200 },
      "2": { realized: 0, future: 10200 },
      "3": { realized: 0, future: 14000 },
      "4": { realized: 0, future: 4400 },
      "5": { realized: 0, future: 3600 },
      "6": { realized: 0, future: 9600 },
    },
  },
  {
    month: "OCT",
    realized: 0,
    future: 53000,
    byProperty: {
      "1": { realized: 0, future: 16500 },
      "2": { realized: 0, future: 11000 },
      "3": { realized: 0, future: 15000 },
      "4": { realized: 0, future: 4700 },
      "5": { realized: 0, future: 4100 },
      "6": { realized: 0, future: 10500 },
    },
  },
  {
    month: "NOV",
    realized: 0,
    future: 48000,
    byProperty: {
      "1": { realized: 0, future: 14800 },
      "2": { realized: 0, future: 10000 },
      "3": { realized: 0, future: 13700 },
      "4": { realized: 0, future: 4200 },
      "5": { realized: 0, future: 3500 },
      "6": { realized: 0, future: 9500 },
    },
  },
  {
    month: "DEC",
    realized: 0,
    future: 55000,
    byProperty: {
      "1": { realized: 0, future: 17000 },
      "2": { realized: 0, future: 11500 },
      "3": { realized: 0, future: 16000 },
      "4": { realized: 0, future: 4800 },
      "5": { realized: 0, future: 4200 },
      "6": { realized: 0, future: 10500 },
    },
  },
]

export const mockMaintenanceAlerts: MaintenanceAlert[] = [
  {
    propertyId: "4",
    propertyName: "City Center Studio",
    endDate: "2025-03-15",
    daysRemaining: 39,
  },
]

export const mockCheckInOuts: CheckInOut[] = [
  {
    id: "1",
    type: "check-in",
    propertyName: "Ocean View Apartment",
    tenantName: "Fatou Jallow",
    date: "2025-02-10",
  },
  {
    id: "2",
    type: "check-out",
    propertyName: "Sunset Villa",
    tenantName: "Lamin Ceesay",
    date: "2025-02-12",
  },
  {
    id: "3",
    type: "check-in",
    propertyName: "Beachfront Bungalow",
    tenantName: "Mariama Sanneh",
    date: "2025-02-15",
  },
]

export const mockPropertyPerformance: Record<string, PropertyPerformance> = {
  "1": {
    lifetimeRevenue: 168000,
    averageOccupancy: 85,
    revPAR: 12750,
    totalBookings: 12,
    averageStayDuration: 28,
  },
  "2": {
    lifetimeRevenue: 96000,
    averageOccupancy: 67,
    revPAR: 8040,
    totalBookings: 8,
    averageStayDuration: 21,
  },
  "3": {
    lifetimeRevenue: 216000,
    averageOccupancy: 90,
    revPAR: 16200,
    totalBookings: 15,
    averageStayDuration: 30,
  },
  "4": {
    lifetimeRevenue: 48000,
    averageOccupancy: 50,
    revPAR: 4000,
    totalBookings: 6,
    averageStayDuration: 14,
  },
  "5": {
    lifetimeRevenue: 120000,
    averageOccupancy: 60,
    revPAR: 12000,
    totalBookings: 6,
    averageStayDuration: 30,
  },
  "6": {
    lifetimeRevenue: 192000,
    averageOccupancy: 80,
    revPAR: 12800,
    totalBookings: 12,
    averageStayDuration: 28,
  },
}

export const mockMaintenanceRecords: Record<string, MaintenanceRecord[]> = {
  "1": [
    {
      id: "m1",
      propertyId: "1",
      date: "2024-12-15",
      description: "AC unit servicing",
      cost: 2500,
      status: "completed",
    },
    {
      id: "m2",
      propertyId: "1",
      date: "2024-11-20",
      description: "Plumbing repair",
      cost: 1800,
      status: "completed",
    },
  ],
  "2": [
    {
      id: "m3",
      propertyId: "2",
      date: "2025-01-10",
      description: "Roof inspection",
      cost: 3000,
      status: "completed",
    },
  ],
  "3": [
    {
      id: "m4",
      propertyId: "3",
      date: "2024-12-05",
      description: "Garden maintenance",
      cost: 1200,
      status: "completed",
    },
  ],
  "4": [
    {
      id: "m5",
      propertyId: "4",
      date: "2025-02-01",
      description: "Kitchen renovation",
      cost: 15000,
      status: "in-progress",
    },
    {
      id: "m6",
      propertyId: "4",
      date: "2024-10-15",
      description: "Electrical wiring update",
      cost: 5000,
      status: "completed",
    },
  ],
  "5": [
    {
      id: "m7",
      propertyId: "5",
      date: "2025-03-01",
      description: "Pool cleaning scheduled",
      cost: 800,
      status: "scheduled",
    },
  ],
  "6": [
    {
      id: "m8",
      propertyId: "6",
      date: "2024-11-30",
      description: "Security system upgrade",
      cost: 4500,
      status: "completed",
    },
  ],
}

export const mockPropertyDocuments: Record<string, PropertyDocument[]> = {
  "1": [
    {
      id: "d1",
      propertyId: "1",
      name: "Property Deed",
      type: "pdf",
      uploadDate: "2024-01-15",
      url: "#",
    },
    {
      id: "d2",
      propertyId: "1",
      name: "Insurance Certificate",
      type: "pdf",
      uploadDate: "2024-06-20",
      url: "#",
    },
    {
      id: "d3",
      propertyId: "1",
      name: "Floor Plan",
      type: "pdf",
      uploadDate: "2024-01-15",
      url: "#",
    },
  ],
  "2": [
    {
      id: "d4",
      propertyId: "2",
      name: "Property Deed",
      type: "pdf",
      uploadDate: "2024-02-10",
      url: "#",
    },
    {
      id: "d5",
      propertyId: "2",
      name: "Safety Inspection Report",
      type: "pdf",
      uploadDate: "2024-12-01",
      url: "#",
    },
  ],
  "3": [
    {
      id: "d6",
      propertyId: "3",
      name: "Property Deed",
      type: "pdf",
      uploadDate: "2024-03-05",
      url: "#",
    },
    {
      id: "d7",
      propertyId: "3",
      name: "Garden Layout Plan",
      type: "pdf",
      uploadDate: "2024-03-10",
      url: "#",
    },
  ],
  "4": [
    {
      id: "d8",
      propertyId: "4",
      name: "Property Deed",
      type: "pdf",
      uploadDate: "2024-04-12",
      url: "#",
    },
    {
      id: "d9",
      propertyId: "4",
      name: "Renovation Permit",
      type: "pdf",
      uploadDate: "2025-01-20",
      url: "#",
    },
  ],
  "5": [
    {
      id: "d10",
      propertyId: "5",
      name: "Property Deed",
      type: "pdf",
      uploadDate: "2024-05-18",
      url: "#",
    },
  ],
  "6": [
    {
      id: "d11",
      propertyId: "6",
      name: "Property Deed",
      type: "pdf",
      uploadDate: "2024-06-22",
      url: "#",
    },
    {
      id: "d12",
      propertyId: "6",
      name: "Security System Manual",
      type: "pdf",
      uploadDate: "2024-11-30",
      url: "#",
    },
  ],
}

export const mockCommunicationLogs: Record<string, CommunicationLog[]> = {
  "1": [
    {
      id: "c1",
      date: "2025-01-15",
      type: "whatsapp",
      message: "Booking confirmation sent",
      sentBy: "System",
    },
    {
      id: "c2",
      date: "2025-01-20",
      type: "email",
      message: "Payment reminder sent",
      sentBy: "Admin",
    },
    {
      id: "c3",
      date: "2025-01-31",
      type: "whatsapp",
      message: "Check-in instructions shared",
      sentBy: "System",
    },
  ],
  "2": [
    {
      id: "c4",
      date: "2025-01-20",
      type: "email",
      message: "Booking confirmation sent",
      sentBy: "System",
    },
    {
      id: "c5",
      date: "2025-02-05",
      type: "phone",
      message: "Discussed special requirements",
      sentBy: "Admin",
    },
  ],
  "3": [
    {
      id: "c6",
      date: "2025-01-25",
      type: "whatsapp",
      message: "Booking confirmation sent",
      sentBy: "System",
    },
  ],
}

export const mockGuestProfiles: Record<string, GuestProfile> = {
  "1": {
    id: "1",
    name: "Fatou Jallow",
    email: "fatou.jallow@email.com",
    phone: "+220 123 4567",
    whatsapp: "+220 123 4567",
    idType: "Passport",
    idNumber: "GM123456",
    emergencyContact: "Amadou Jallow",
    emergencyPhone: "+220 987 6543",
    notes: "Prefers ground floor units",
    previousStays: 3,
    lifetimeValue: 42000,
    averageRating: 4.8,
    isRepeatGuest: true,
  },
  "2": {
    id: "2",
    name: "Lamin Ceesay",
    email: "lamin.ceesay@email.com",
    phone: "+220 234 5678",
    whatsapp: "+220 234 5678",
    idType: "National ID",
    idNumber: "GM234567",
    emergencyContact: "Isatou Ceesay",
    emergencyPhone: "+220 876 5432",
    previousStays: 2,
    lifetimeValue: 34000,
    averageRating: 4.5,
    isRepeatGuest: true,
  },
  "3": {
    id: "3",
    name: "Mariama Sanneh",
    email: "mariama.sanneh@email.com",
    phone: "+220 345 6789",
    whatsapp: "+220 345 6789",
    idType: "Passport",
    idNumber: "GM345678",
    emergencyContact: "Ousman Sanneh",
    emergencyPhone: "+220 765 4321",
    notes: "Vegetarian meals preferred",
    previousStays: 1,
    lifetimeValue: 15500,
    averageRating: 4.8,
    isRepeatGuest: false,
  },
}

export const mockPaymentRecords: Record<string, PaymentRecord[]> = {
  "1": [
    {
      id: "p1",
      date: "2025-01-15",
      amount: 14000,
      method: "Bank Transfer",
      status: "paid",
    },
  ],
  "2": [
    {
      id: "p2",
      date: "2025-01-20",
      amount: 8500,
      method: "Mobile Money",
      status: "paid",
    },
    {
      id: "p3",
      date: "2025-02-10",
      amount: 8500,
      method: "Mobile Money",
      status: "pending",
    },
  ],
  "3": [
    {
      id: "p4",
      date: "2025-01-25",
      amount: 15500,
      method: "Cash",
      status: "paid",
    },
  ],
}

export const mockReservationDocuments: Record<string, ReservationDocument[]> = {
  "1": [
    {
      id: "rd1",
      name: "Invoice #INV-001",
      type: "invoice",
      uploadDate: "2025-01-15",
      url: "#",
    },
    {
      id: "rd2",
      name: "Rental Agreement",
      type: "agreement",
      uploadDate: "2025-01-15",
      url: "#",
    },
    {
      id: "rd3",
      name: "Payment Receipt",
      type: "receipt",
      uploadDate: "2025-01-15",
      url: "#",
    },
  ],
  "2": [
    {
      id: "rd4",
      name: "Invoice #INV-002",
      type: "invoice",
      uploadDate: "2025-01-20",
      url: "#",
    },
    {
      id: "rd5",
      name: "Rental Agreement",
      type: "agreement",
      uploadDate: "2025-01-20",
      url: "#",
    },
  ],
  "3": [
    {
      id: "rd6",
      name: "Invoice #INV-003",
      type: "invoice",
      uploadDate: "2025-01-25",
      url: "#",
    },
    {
      id: "rd7",
      name: "Rental Agreement",
      type: "agreement",
      uploadDate: "2025-01-25",
      url: "#",
    },
    {
      id: "rd8",
      name: "ID Copy",
      type: "id-copy",
      uploadDate: "2025-01-25",
      url: "#",
    },
  ],
}

export const mockReservationDetails: Record<string, ReservationDetail> = {
  "1": {
    ...mockReservations[0],
    reservationNumber: "RES-2025-001",
    status: "checked-in",
    guests: {
      adults: 2,
      children: 0,
    },
    specialRequests: "Late check-in requested",
    totalAmount: 14000,
    paidAmount: 14000,
    balanceAmount: 0,
    paymentMethod: "Bank Transfer",
    securityDeposit: 2000,
    securityDepositStatus: "paid",
  },
  "2": {
    ...mockReservations[1],
    reservationNumber: "RES-2025-002",
    status: "confirmed",
    guests: {
      adults: 1,
      children: 1,
    },
    specialRequests: "Extra bed for child",
    totalAmount: 17000,
    paidAmount: 8500,
    balanceAmount: 8500,
    balanceDueDate: "2025-02-15",
    paymentMethod: "Mobile Money",
    securityDeposit: 2500,
    securityDepositStatus: "pending",
  },
  "3": {
    ...mockReservations[2],
    reservationNumber: "RES-2025-003",
    status: "confirmed",
    guests: {
      adults: 2,
      children: 2,
    },
    specialRequests: "",
    totalAmount: 15500,
    paidAmount: 15500,
    balanceAmount: 0,
    paymentMethod: "Cash",
    securityDeposit: 2000,
    securityDepositStatus: "paid",
  },
}

export const mockBlockedDates: BlockedDate[] = [
  {
    id: "b1",
    propertyId: "4",
    startDate: "2025-02-01",
    endDate: "2025-03-15",
    reason: "maintenance",
    notes: "Kitchen renovation in progress",
  },
  {
    id: "b2",
    propertyId: "2",
    startDate: "2025-03-20",
    endDate: "2025-03-25",
    reason: "owner-use",
    notes: "Owner visiting",
  },
  {
    id: "b3",
    propertyId: "5",
    startDate: "2025-02-28",
    endDate: "2025-03-05",
    reason: "maintenance",
    notes: "Pool maintenance scheduled",
  },
  {
    id: "b4",
    propertyId: "6",
    startDate: "2025-02-01",
    endDate: "2025-02-07",
    reason: "maintenance",
    notes: "Annual deep cleaning",
  },
  {
    id: "b5",
    propertyId: "3",
    startDate: "2025-02-01",
    endDate: "2025-02-05",
    reason: "owner-use",
    notes: "Owner personal use",
  },
  {
    id: "b6",
    propertyId: "1",
    startDate: "2025-03-20",
    endDate: "2025-03-25",
    reason: "maintenance",
    notes: "AC system upgrade",
  },
]

export const mockExpenses: Expense[] = [
  {
    id: "e1",
    amount: 2500,
    description: "AC unit servicing",
    category: "Maintenance",
    property: "1",
    date: "2024-12-15",
    receiptUrl: "#",
  },
  {
    id: "e2",
    amount: 1800,
    description: "Plumbing repair",
    category: "Maintenance",
    property: "1",
    date: "2024-11-20",
  },
  {
    id: "e3",
    amount: 3200,
    description: "Electricity bill - Q4",
    category: "Utilities",
    property: "Portfolio Wide",
    date: "2024-12-01",
    receiptUrl: "#",
  },
  {
    id: "e4",
    amount: 5000,
    description: "Property insurance renewal",
    category: "Insurance",
    property: "Portfolio Wide",
    date: "2024-11-15",
    receiptUrl: "#",
  },
  {
    id: "e5",
    amount: 3000,
    description: "Roof inspection",
    category: "Maintenance",
    property: "2",
    date: "2025-01-10",
  },
  {
    id: "e6",
    amount: 1200,
    description: "Garden maintenance",
    category: "Maintenance",
    property: "3",
    date: "2024-12-05",
    receiptUrl: "#",
  },
  {
    id: "e7",
    amount: 2800,
    description: "Water bill - Q4",
    category: "Utilities",
    property: "Portfolio Wide",
    date: "2024-12-10",
  },
]

export const mockFinancialOverview: FinancialOverview = {
  ytdRevenue: 45200,
  ytdExpenses: 18400,
  ytdProfit: 26800,
  revenueTrend: 12,
  expensesTrend: 8,
  profitTrend: 15,
}

export const mockProfitLossData: ProfitLossData[] = [
  { month: "Jan", realizedProfit: 24000, projectedProfit: 0, realizedLoss: 0, projectedLoss: 0 },
  { month: "Feb", realizedProfit: 27000, projectedProfit: 0, realizedLoss: 0, projectedLoss: 0 },
  { month: "Mar", realizedProfit: 0, projectedProfit: 28000, realizedLoss: 0, projectedLoss: 0 },
  { month: "Apr", realizedProfit: 0, projectedProfit: 32000, realizedLoss: 0, projectedLoss: 0 },
  { month: "May", realizedProfit: 0, projectedProfit: 25000, realizedLoss: 0, projectedLoss: 0 },
  { month: "Jun", realizedProfit: 0, projectedProfit: 30000, realizedLoss: 0, projectedLoss: 0 },
  { month: "Jul", realizedProfit: 0, projectedProfit: 27000, realizedLoss: 0, projectedLoss: 0 },
  { month: "Aug", realizedProfit: 0, projectedProfit: 31000, realizedLoss: 0, projectedLoss: 0 },
  { month: "Sep", realizedProfit: 0, projectedProfit: 29000, realizedLoss: 0, projectedLoss: 0 },
  { month: "Oct", realizedProfit: 0, projectedProfit: 33000, realizedLoss: 0, projectedLoss: 0 },
  { month: "Nov", realizedProfit: 0, projectedProfit: 28000, realizedLoss: 0, projectedLoss: 0 },
  { month: "Dec", realizedProfit: 0, projectedProfit: 35000, realizedLoss: 0, projectedLoss: 0 },
]

export const mockOccupancyRateData: OccupancyRateData[] = [
  {
    month: "Jan",
    portfolioAverage: 82,
    properties: {
      "1": 85,
      "2": 70,
      "3": 90,
      "4": 55,
      "5": 65,
      "6": 80,
    },
  },
  {
    month: "Feb",
    portfolioAverage: 87,
    properties: {
      "1": 88,
      "2": 75,
      "3": 94,
      "4": 60,
      "5": 72,
      "6": 85,
    },
  },
  {
    month: "Mar",
    portfolioAverage: 85,
    properties: {
      "1": 87,
      "2": 73,
      "3": 92,
      "4": 58,
      "5": 70,
      "6": 83,
    },
  },
  {
    month: "Apr",
    portfolioAverage: 89,
    properties: {
      "1": 90,
      "2": 78,
      "3": 95,
      "4": 65,
      "5": 75,
      "6": 88,
    },
  },
  {
    month: "May",
    portfolioAverage: 84,
    properties: {
      "1": 86,
      "2": 72,
      "3": 91,
      "4": 57,
      "5": 68,
      "6": 82,
    },
  },
  {
    month: "Jun",
    portfolioAverage: 88,
    properties: {
      "1": 89,
      "2": 76,
      "3": 93,
      "4": 62,
      "5": 73,
      "6": 86,
    },
  },
  {
    month: "Jul",
    portfolioAverage: 86,
    properties: {
      "1": 88,
      "2": 74,
      "3": 92,
      "4": 59,
      "5": 71,
      "6": 84,
    },
  },
  {
    month: "Aug",
    portfolioAverage: 90,
    properties: {
      "1": 91,
      "2": 79,
      "3": 96,
      "4": 66,
      "5": 76,
      "6": 89,
    },
  },
  {
    month: "Sep",
    portfolioAverage: 87,
    properties: {
      "1": 89,
      "2": 75,
      "3": 93,
      "4": 61,
      "5": 73,
      "6": 86,
    },
  },
  {
    month: "Oct",
    portfolioAverage: 91,
    properties: {
      "1": 92,
      "2": 80,
      "3": 97,
      "4": 68,
      "5": 78,
      "6": 90,
    },
  },
  {
    month: "Nov",
    portfolioAverage: 88,
    properties: {
      "1": 90,
      "2": 77,
      "3": 94,
      "4": 63,
      "5": 74,
      "6": 87,
    },
  },
  {
    month: "Dec",
    portfolioAverage: 93,
    properties: {
      "1": 94,
      "2": 82,
      "3": 98,
      "4": 70,
      "5": 80,
      "6": 92,
    },
  },
]

export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    date: "2025-02-01",
    description: "Rent payment - Sunset Villa",
    type: "payment",
    property: "1",
    amount: 14000,
    status: "completed",
  },
  {
    id: "t2",
    date: "2025-02-01",
    description: "AC unit servicing",
    type: "expense",
    property: "1",
    amount: -2500,
    status: "completed",
  },
  {
    id: "t3",
    date: "2025-02-05",
    description: "Electricity bill - Q4",
    type: "expense",
    property: "Portfolio Wide",
    amount: -3200,
    status: "completed",
  },
  {
    id: "t4",
    date: "2025-02-10",
    description: "Rent payment - Garden House",
    type: "payment",
    property: "3",
    amount: 17000,
    status: "completed",
  },
  {
    id: "t5",
    date: "2025-02-10",
    description: "Roof inspection",
    type: "expense",
    property: "2",
    amount: -3000,
    status: "completed",
  },
  {
    id: "t6",
    date: "2025-02-15",
    description: "Rent payment - Palm Residence",
    type: "payment",
    property: "6",
    amount: 15500,
    status: "completed",
  },
  {
    id: "t7",
    date: "2025-02-15",
    description: "Property insurance renewal",
    type: "expense",
    property: "Portfolio Wide",
    amount: -5000,
    status: "pending",
  },
  {
    id: "t8",
    date: "2025-02-20",
    description: "Garden maintenance",
    type: "expense",
    property: "3",
    amount: -1200,
    status: "completed",
  },
]

export const mockRevenueTimelineData: RevenueTimelineData[] = [
  {
    month: "Jan",
    properties: {
      "1": 14000,
      "2": 8000,
      "3": 12000,
      "4": 3500,
      "5": 2500,
      "6": 8000,
    },
  },
  {
    month: "Feb",
    properties: {
      "1": 15000,
      "2": 9500,
      "3": 13000,
      "4": 4000,
      "5": 3000,
      "6": 9000,
    },
  },
  {
    month: "Mar",
    properties: {
      "1": 15000,
      "2": 10000,
      "3": 14000,
      "4": 4200,
      "5": 3500,
      "6": 9000,
    },
  },
  {
    month: "Apr",
    properties: {
      "1": 16000,
      "2": 11000,
      "3": 15000,
      "4": 4500,
      "5": 4000,
      "6": 10000,
    },
  },
  {
    month: "May",
    properties: {
      "1": 14000,
      "2": 9000,
      "3": 13000,
      "4": 3800,
      "5": 3200,
      "6": 9000,
    },
  },
  {
    month: "Jun",
    properties: {
      "1": 15500,
      "2": 10500,
      "3": 14000,
      "4": 4300,
      "5": 3700,
      "6": 10000,
    },
  },
]

export const mockADRData: ADRData[] = [
  {
    month: "Jan",
    properties: {
      "1": 467,
      "2": 400,
      "3": 500,
      "4": 267,
      "5": 667,
      "6": 516,
    },
    marketADR: 450,
  },
  {
    month: "Feb",
    properties: {
      "1": 482,
      "2": 422,
      "3": 520,
      "4": 280,
      "5": 690,
      "6": 530,
    },
    marketADR: 465,
  },
  {
    month: "Mar",
    properties: {
      "1": 490,
      "2": 435,
      "3": 535,
      "4": 290,
      "5": 710,
      "6": 545,
    },
    marketADR: 475,
  },
  {
    month: "Apr",
    properties: {
      "1": 517,
      "2": 458,
      "3": 560,
      "4": 310,
      "5": 740,
      "6": 570,
    },
    marketADR: 490,
  },
  {
    month: "May",
    properties: {
      "1": 473,
      "2": 410,
      "3": 510,
      "4": 275,
      "5": 680,
      "6": 525,
    },
    marketADR: 460,
  },
  {
    month: "Jun",
    properties: {
      "1": 500,
      "2": 445,
      "3": 540,
      "4": 300,
      "5": 720,
      "6": 555,
    },
    marketADR: 480,
  },
  {
    month: "Jul",
    properties: {
      "1": 485,
      "2": 425,
      "3": 525,
      "4": 285,
      "5": 700,
      "6": 540,
    },
    marketADR: 470,
  },
  {
    month: "Aug",
    properties: {
      "1": 505,
      "2": 450,
      "3": 550,
      "4": 305,
      "5": 730,
      "6": 565,
    },
    marketADR: 485,
  },
  {
    month: "Sep",
    properties: {
      "1": 495,
      "2": 438,
      "3": 542,
      "4": 295,
      "5": 715,
      "6": 552,
    },
    marketADR: 478,
  },
  {
    month: "Oct",
    properties: {
      "1": 520,
      "2": 465,
      "3": 570,
      "4": 320,
      "5": 750,
      "6": 580,
    },
    marketADR: 495,
  },
  {
    month: "Nov",
    properties: {
      "1": 488,
      "2": 430,
      "3": 530,
      "4": 288,
      "5": 705,
      "6": 548,
    },
    marketADR: 472,
  },
  {
    month: "Dec",
    properties: {
      "1": 530,
      "2": 475,
      "3": 580,
      "4": 330,
      "5": 770,
      "6": 595,
    },
    marketADR: 505,
  },
]

export const mockPropertyPerformanceMetrics: PropertyPerformanceMetrics[] = [
  {
    propertyId: "1",
    propertyName: "Sunset Villa",
    revenue: 89500,
    occupancy: 85,
    adr: 500,
    revPAR: 425,
    trend: 12,
  },
  {
    propertyId: "3",
    propertyName: "Garden House",
    revenue: 81000,
    occupancy: 90,
    adr: 540,
    revPAR: 486,
    trend: 15,
  },
  {
    propertyId: "6",
    propertyName: "Palm Residence",
    revenue: 55000,
    occupancy: 80,
    adr: 516,
    revPAR: 413,
    trend: 8,
  },
  {
    propertyId: "2",
    propertyName: "Ocean View Apartment",
    revenue: 58000,
    occupancy: 67,
    adr: 400,
    revPAR: 268,
    trend: 5,
  },
  {
    propertyId: "5",
    propertyName: "Beachfront Bungalow",
    revenue: 19900,
    occupancy: 60,
    adr: 667,
    revPAR: 400,
    trend: -3,
  },
  {
    propertyId: "4",
    propertyName: "City Center Studio",
    revenue: 23000,
    occupancy: 50,
    adr: 267,
    revPAR: 134,
    trend: -8,
  },
]

export const mockBudgets: Budget[] = [
  {
    id: "b1",
    category: "Maintenance",
    monthlyLimit: 5000,
    ytdSpent: 8500,
    ytdLimit: 10000,
    status: "near",
  },
  {
    id: "b2",
    category: "Utilities",
    monthlyLimit: 4000,
    ytdSpent: 6000,
    ytdLimit: 8000,
    status: "under",
  },
  {
    id: "b3",
    category: "Insurance",
    monthlyLimit: 2500,
    ytdSpent: 5000,
    ytdLimit: 5000,
    status: "under",
  },
  {
    id: "b4",
    category: "Taxes",
    monthlyLimit: 3000,
    ytdSpent: 6500,
    ytdLimit: 6000,
    status: "over",
  },
]

export const mockRecurringExpenses: RecurringExpense[] = [
  {
    id: "r1",
    description: "Property insurance premium",
    category: "Insurance",
    amount: 2500,
    frequency: "quarterly",
    nextDueDate: "2025-03-15",
    property: "Portfolio Wide",
  },
  {
    id: "r2",
    description: "Electricity bill",
    category: "Utilities",
    amount: 1600,
    frequency: "monthly",
    nextDueDate: "2025-03-01",
    property: "Portfolio Wide",
  },
  {
    id: "r3",
    description: "Water bill",
    category: "Utilities",
    amount: 1400,
    frequency: "monthly",
    nextDueDate: "2025-03-01",
    property: "Portfolio Wide",
  },
  {
    id: "r4",
    description: "Property tax",
    category: "Taxes",
    amount: 3000,
    frequency: "quarterly",
    nextDueDate: "2025-04-01",
    property: "Portfolio Wide",
  },
]

export const mockExpenseTrendData: ExpenseTrendData[] = [
  { month: "Jan", amount: 8200 },
  { month: "Feb", amount: 9500 },
  { month: "Mar", amount: 7800 },
  { month: "Apr", amount: 10200 },
  { month: "May", amount: 8900 },
  { month: "Jun", amount: 9700 },
  { month: "Jul", amount: 8500 },
  { month: "Aug", amount: 9200 },
  { month: "Sep", amount: 8700 },
  { month: "Oct", amount: 10500 },
  { month: "Nov", amount: 9100 },
  { month: "Dec", amount: 9800 },
]

export const mockPropertyExpenseComparison: PropertyExpenseComparison[] = [
  {
    propertyId: "1",
    propertyName: "Sunset Villa",
    totalExpenses: 4300,
    maintenanceCost: 2500,
    utilitiesCost: 1200,
    otherCosts: 600,
  },
  {
    propertyId: "2",
    propertyName: "Ocean View Apartment",
    totalExpenses: 3000,
    maintenanceCost: 1800,
    utilitiesCost: 900,
    otherCosts: 300,
  },
  {
    propertyId: "3",
    propertyName: "Garden House",
    totalExpenses: 3700,
    maintenanceCost: 1200,
    utilitiesCost: 1500,
    otherCosts: 1000,
  },
  {
    propertyId: "4",
    propertyName: "City Center Studio",
    totalExpenses: 15000,
    maintenanceCost: 14000,
    utilitiesCost: 800,
    otherCosts: 200,
  },
  {
    propertyId: "5",
    propertyName: "Beachfront Bungalow",
    totalExpenses: 800,
    maintenanceCost: 0,
    utilitiesCost: 600,
    otherCosts: 200,
  },
  {
    propertyId: "6",
    propertyName: "Palm Residence",
    totalExpenses: 4500,
    maintenanceCost: 3000,
    utilitiesCost: 1000,
    otherCosts: 500,
  },
]
